name: PSReadLine-$(Date:yyyyMMdd).$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - ci
pr:
  branches:
    include:
    - master
    - ci

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  PSREADLINE_TESTRUN: 1

stages:
- stage: PSReadLine
  jobs:
  - job: Build & Test
    pool:
      vmImage: windows-latest

    steps:

    - pwsh: |
        Write-Host "PS Version: $($PSVersionTable.PSVersion)"
        Set-Location -Path '$(Build.SourcesDirectory)'
        .\build.ps1 -Bootstrap
        .\build.ps1 -Configuration Release -Framework net462

        $output = '$(Build.SourcesDirectory)\bin\Release\PSReadLine'
        Write-Host "##vso[artifact.upload containerfolder=PSReadLine;artifactname=PSReadLine]$output"
      displayName: Bootstrap & Build

    - pwsh: |
        Set-Location -Path '$(Build.SourcesDirectory)'
        .\build.ps1 -Test -Configuration Release -Framework net462
      displayName: Test
